site_page_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SitePageBundle:Default:index }

SitePageBundle_homepage:
    pattern:  /
    defaults: { _controller: SitePageBundle:Page:index }
    requirements:
        _method:  GET